### ISSUE TITLE
Bug in ClassLayer?

### ISSUE THREAD

**Issue by fjean** [dongzhang89/SR-SS#3]
In the `forward` method of class `ClassLayer` in `lib/models.deeplab.py`:

```python
def forward(self, x):
        x = self.layer(x)
        x = self.classification(x)
        pred = x.view(x.shape[0], -1)
        pred = torch.sigmoid(self.fc(pred))
        return x, pred
```

the returned `x` does not represent feature maps anymore because `self.classification` is an `AdaptiveAvgPooling2D` with `output_size=1`, and thus returns a tensor with shape BxCx1x1. Then this is resized to the size of the image later, which doesn't seem to make sense.

Shouldn't it be like this?

```python
def forward(self, x):
        x = self.layer(x)
        pred = self.classification(x)
        pred = pred.view(pred.shape[0], -1)
        pred = torch.sigmoid(self.fc(pred))
        return x, pred
```

**Comment by dongzhang89** [comment]
@fjean  Thank you for your reminding. This bug has been fixed.
